
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author desenvolvimento3
 */
public class FormAluno extends javax.swing.JFrame {

    SessionFactory fabrica = new Configuration().configure().buildSessionFactory();
    List<Aluno> listaAluno = new ArrayList<>();
    int posicaoAtual = 0;
    int tamanhoLista = 0;

    /**
     * Creates new form FormAluno
     */
    public FormAluno() {
        initComponents();
        preencherJtable();
        jTable1.setSelectionBackground(Color.gray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        textCurso = new javax.swing.JTextField();
        textCidade = new javax.swing.JTextField();
        textFone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        novoButton = new javax.swing.JButton();
        excluirButton = new javax.swing.JButton();
        alterarButton = new javax.swing.JButton();
        salvarButton = new javax.swing.JButton();
        textId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comecoButton = new javax.swing.JButton();
        anteriorButton = new javax.swing.JButton();
        proximoButton = new javax.swing.JButton();
        ultimoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Cadastro");

        jLabel2.setText("Nome:");

        jLabel3.setText("Curso:");

        jLabel4.setText("Cidade:");

        jLabel5.setText("Fone:");

        textNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Curso", "Cidade", "Fone"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        novoButton.setText("Novo");
        novoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoButtonActionPerformed(evt);
            }
        });

        excluirButton.setText("Excluir");
        excluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirButtonActionPerformed(evt);
            }
        });

        alterarButton.setText("Alterar");
        alterarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarButtonActionPerformed(evt);
            }
        });

        salvarButton.setText("Salvar");
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });

        textId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIdActionPerformed(evt);
            }
        });

        jLabel6.setText("Id:");

        comecoButton.setText("|<");
        comecoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comecoButtonActionPerformed(evt);
            }
        });

        anteriorButton.setText("<");
        anteriorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorButtonActionPerformed(evt);
            }
        });

        proximoButton.setText(">");
        proximoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoButtonActionPerformed(evt);
            }
        });

        ultimoButton.setText(">|");
        ultimoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textFone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jLabel1))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(novoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salvarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alterarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluirButton)
                        .addGap(14, 14, 14))))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(comecoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anteriorButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proximoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ultimoButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comecoButton)
                    .addComponent(anteriorButton)
                    .addComponent(proximoButton)
                    .addComponent(ultimoButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novoButton)
                    .addComponent(excluirButton)
                    .addComponent(alterarButton)
                    .addComponent(salvarButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_textNomeActionPerformed

    private void novoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoButtonActionPerformed
        // TODO add your handling code here:
        textId.setText("");
        textNome.setText("");
        textCurso.setText("");
        textCidade.setText("");
        textFone.setText("");
    }//GEN-LAST:event_novoButtonActionPerformed

    private void alterarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarButtonActionPerformed
        // TODO add your handling code here:

        Session sessao = fabrica.openSession();
        Aluno aluno = new Aluno();
        aluno.setAluCodigo(Integer.parseInt(textId.getText()));
        aluno.setAluNome(textNome.getText());
        aluno.setAluCidade(textCidade.getText());
        aluno.setAluCurso(textCurso.getText());
        aluno.setAluFone(textFone.getText());

        Transaction tr_aluno = sessao.beginTransaction();
        sessao.update(aluno);
        tr_aluno.commit();
        sessao.close();
        preencherJtable();
    }//GEN-LAST:event_alterarButtonActionPerformed

    private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed
        // TODO add your handling code here:
        try {
            Session sessao = fabrica.openSession();
            Aluno aluno = new Aluno();

            aluno.setAluCodigo(Integer.parseInt(textId.getText()));
            aluno.setAluNome(textNome.getText());
            aluno.setAluCidade(textCidade.getText());
            aluno.setAluCurso(textCurso.getText());
            aluno.setAluFone(textFone.getText());

            Transaction tr_aluno = sessao.beginTransaction();
            sessao.save(aluno);
            tr_aluno.commit();
            sessao.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        preencherJtable();
    }//GEN-LAST:event_salvarButtonActionPerformed


    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int linha = jTable1.getSelectedRow();

        textId.setText(jTable1.getValueAt(linha, 0).toString());
        textNome.setText(jTable1.getValueAt(linha, 1).toString());
        textCurso.setText(jTable1.getValueAt(linha, 2).toString());
        textCidade.setText(jTable1.getValueAt(linha, 3).toString());
        textFone.setText(jTable1.getValueAt(linha, 4).toString());

//        Aluno aluno = new Aluno();
//        aluno.setAluNome(jTable1.getValueAt(linha, 0).toString());
//        aluno.setAluCurso(jTable1.getValueAt(linha, 1).toString());
//        aluno.setAluCidade(jTable1.getValueAt(linha, 2).toString());
//        aluno.setAluFone(jTable1.getValueAt(linha, 3).toString());
//        
//        textNome.setText(aluno.getAluCidade());
//        textCurso.setText(aluno.getAluCurso());
//        textCidade.setText(aluno.getAluCidade());
//        textFone.setText(aluno.getAluFone());

    }//GEN-LAST:event_jTable1MouseClicked

    private void excluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirButtonActionPerformed
        // TODO add your handling code here:
        String nome = "Deseja excluir " + textNome.getText() + " ?";
        int escolha = JOptionPane.showConfirmDialog(null, nome, "Exclusão", JOptionPane.YES_OPTION);
        if (escolha == JOptionPane.YES_OPTION) {

            try {
                Session sessao = fabrica.openSession();
                Aluno aluno = new Aluno();
                posicaoAtual = Integer.parseInt(textId.getText());
                aluno.setAluCodigo(Integer.parseInt(textId.getText()));

                Transaction tr_aluno = sessao.beginTransaction();
                sessao.delete(aluno);
                tr_aluno.commit();
                sessao.close();
                JOptionPane.showMessageDialog(null, "Excluido com sucesso");
                preencherJtable();
                textId.setText(Integer.toString(aluno.getAluCodigo()));
                textNome.setText(aluno.getAluNome());
                textCurso.setText(aluno.getAluCurso());
                textCidade.setText(aluno.getAluCidade());
                textFone.setText(aluno.getAluFone());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }


    }//GEN-LAST:event_excluirButtonActionPerformed

    private void textIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIdActionPerformed

    private void comecoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comecoButtonActionPerformed
        // TODO add your handling code here:
        Aluno aluno = listaAluno.get(0);
        textId.setText(Integer.toString(aluno.getAluCodigo()));
        textNome.setText(aluno.getAluNome());
        textCurso.setText(aluno.getAluCurso());
        textCidade.setText(aluno.getAluCidade());
        textFone.setText(aluno.getAluFone());
        posicaoAtual = 0;
    }//GEN-LAST:event_comecoButtonActionPerformed

    private void anteriorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorButtonActionPerformed
        // TODO add your handling code here:
        if (posicaoAtual > 0) {

            Aluno aluno = listaAluno.get(posicaoAtual - 1);
            textId.setText(Integer.toString(aluno.getAluCodigo()));
            textNome.setText(aluno.getAluNome());
            textCurso.setText(aluno.getAluCurso());
            textCidade.setText(aluno.getAluCidade());
            textFone.setText(aluno.getAluFone());
            posicaoAtual--;
        }
    }//GEN-LAST:event_anteriorButtonActionPerformed

    private void proximoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoButtonActionPerformed
        // TODO add your handling code here:
        if (posicaoAtual < tamanhoLista - 1) {

            posicaoAtual++;
            Aluno aluno = listaAluno.get(posicaoAtual);
            textId.setText(Integer.toString(aluno.getAluCodigo()));
            textNome.setText(aluno.getAluNome());
            textCurso.setText(aluno.getAluCurso());
            textCidade.setText(aluno.getAluCidade());
            textFone.setText(aluno.getAluFone());
        }
    }//GEN-LAST:event_proximoButtonActionPerformed

    private void ultimoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimoButtonActionPerformed
        // TODO add your handling code here:

        Aluno aluno = listaAluno.get(tamanhoLista - 1);
        textId.setText(Integer.toString(aluno.getAluCodigo()));
        textNome.setText(aluno.getAluNome());
        textCurso.setText(aluno.getAluCurso());
        textCidade.setText(aluno.getAluCidade());
        textFone.setText(aluno.getAluFone());
        posicaoAtual = tamanhoLista - 1;


    }//GEN-LAST:event_ultimoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarButton;
    private javax.swing.JButton anteriorButton;
    private javax.swing.JButton comecoButton;
    private javax.swing.JButton excluirButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton novoButton;
    private javax.swing.JButton proximoButton;
    private javax.swing.JButton salvarButton;
    private javax.swing.JTextField textCidade;
    private javax.swing.JTextField textCurso;
    private javax.swing.JTextField textFone;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textNome;
    private javax.swing.JButton ultimoButton;
    // End of variables declaration//GEN-END:variables

    public void preencherJtable() {

        jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(60);

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);

        SessionFactory fabrica = new Configuration().configure().buildSessionFactory();
        Session sessao = fabrica.openSession();

        listaAluno = sessao.createQuery("FROM Aluno").list();

        tamanhoLista = listaAluno.size();

        for (int i = 0; i < tamanhoLista; i++) {
            Aluno aluno = listaAluno.get(i);

//            if (i == 0) {
//                textNome.setText(aluno.getAluNome());
//                textCurso.setText(aluno.getAluCurso());
//                textCidade.setText(aluno.getAluCidade());
//                textFone.setText(aluno.getAluFone());
//            }
            modelo.addRow(new Object[]{aluno.getAluCodigo(), aluno.getAluNome(), aluno.getAluCurso(), aluno.getAluCidade(), aluno.getAluFone()});
            System.out.println(aluno.toString());

        }
        if (!listaAluno.isEmpty()) {
            Aluno aluno = listaAluno.get(0);
            textId.setText(Integer.toString(aluno.getAluCodigo()));
            textNome.setText(aluno.getAluNome());
            textCurso.setText(aluno.getAluCurso());
            textCidade.setText(aluno.getAluCidade());
            textFone.setText(aluno.getAluFone());
        }

    }

}
